name: EcoMC
version: ${projectVersion}
main: com.willfp.ecomc.EcoMCPlugin
api-version: 1.17
authors: [ Auxilor ]
website: willfp.com
load: STARTUP
depend:
  - eco
  - EcoSkills
  - EcoEnchants
  - EcoItems
  - EcoArmor
  - Reforges
  - Talismans
  - EcoBosses

commands:
  secretecomcadmincommand:
    description: Secret EcoMC Admin Command
    permission: ecomc.secretecomcadminpermission
  crystals:
    description: Get crystals
    permission: ecomc.crystals
    aliases:
      - crystal
      - crystalshop
      - cshop
  trails:
    description: Open trails menu
    permission: ecomc.trails
  geodes:
    description: Crack open geodes
    permission: ecomc.geodes
    aliases:
      - geode
      - geodes

permissions:
  ecomc.secretecomcadminpermission:
    default: op
  ecomc.crystals.*:
    children:
      ecomc.crystals: true
      ecomc.crystals.give: true
      ecomc.crystals.get: true
      ecomc.crystals.set: true
      ecomc.crystals.shop: true
      ecomc.crystals.geodes: true
      ecomc.crystals.expirepotion: true
    default: op
  ecomc.bosses:
    default: true
  ecomc.crystals:
    default: true
  ecomc.geodes:
    default: true
  ecomc.trails:
    default: true
  ecomc.trails.set:
    default: op
  ecomc.crystals.give:
    default: op
  ecomc.crystals.get:
    default: op
  ecomc.crystals.set:
    default: op
  ecomc.crystals.expirepotion:
    default: op
  ecomc.crystals.shop:
    default: true
  ecomc.crystals.geodes:
    default: true
