name: EcoMC
version: ${projectVersion}
main: com.willfp.ecomc.EcoMCPlugin
api-version: 1.17
authors: [ Auxilor ]
website: willfp.com
load: STARTUP
depend:
  - eco
  - EcoSkills
  - EcoEnchants

commands:
  secretecomcadmincommand:
    description: Secret EcoMC Admin Command
    permission: ecomc.secretecomcadminpermission
  crystals:
    description: Get crystals
    permission: ecomc.crystals
    aliases:
      - crystal
      - geode
      - geodes
      - crystalshop
      - cshop
      - geodeshop

permissions:
  secretecomcadminpermission:
    default: op
  ecomc.crystals.*:
    children:
      ecomc.crystals: true
      ecomc.crystals.give: true
      ecomc.crystals.get: true
      ecomc.crystals.shop: true
      ecomc.crystals.geodes: true
      ecomc.crystals.expirepotion: true
    default: op
  ecomc.crystals:
    default: true
  ecomc.crystals.give:
    default: op
  ecomc.crystals.get:
    default: op
  ecomc.crystals.expirepotion:
    default: op
  ecomc.crystals.shop:
    default: true
  ecomc.crystals.geodes:
    default: true
