name: EcoMC
version: ${projectVersion}
main: com.willfp.ecomc.EcoMCPlugin
api-version: 1.17
authors: [ Auxilor ]
website: willfp.com
load: STARTUP
depend:
  - eco
  - EcoSkills

commands:
  crystals:
    description: Get crystals
    permission: ecomc.crystals

permissions:
  ecomc.crystals:
    default: true
  ecomc.crystals.give:
    default: op
  ecomc.crystals.get:
    default: op
